import "server-only";
import { randomUUID } from "node:crypto";
import type { CurrentPrincipal } from "@/lib/auth/principal";
import { getPrisma } from "@/lib/db/prisma";
import { providerHostIsBlocked } from "@/lib/llm/networkPolicy";
import { decryptProviderSecret, encryptProviderSecret } from "@/lib/llm/secretBox";

export type WireApi = "chat_completions" | "responses" | "anthropic_messages";
export type ProviderConfigDto = { id: string; name: string; baseUrl: string; model: string; wireApi: WireApi; hasApiKey: boolean };
export type ModelPresetDto = { id: string; name: string; providerId: string; model: string; temperature: number; maxTokens: number };
type StoredProvider = ProviderConfigDto & { ownerId: string; encryptedApiKey?: string | null };
type StoredPreset = ModelPresetDto & { ownerId: string };
export class ProviderError extends Error { constructor(public code: "BAD_REQUEST" | "NOT_FOUND" | "FORBIDDEN", message: string) { super(message); } }
let inMemoryForTest = false; let providers: StoredProvider[] = []; let presets: StoredPreset[] = [];
export function resetProviderRepositoryForTest() { inMemoryForTest = true; providers = []; presets = []; }
export function restoreProviderRepositoryForTest() { inMemoryForTest = false; }
function requireEncryption() { encryptProviderSecret(""); }
function dto(p: StoredProvider): ProviderConfigDto { return { id: p.id, name: p.name, baseUrl: p.baseUrl, model: p.model, wireApi: p.wireApi, hasApiKey: Boolean(p.encryptedApiKey) }; }
export function validateProviderBaseUrl(baseUrl: string) { let url: URL; try { url = new URL(baseUrl); } catch { throw new ProviderError("BAD_REQUEST", "Provider URL is invalid"); } if (url.protocol !== "https:" || url.username || url.password || url.search || url.hash || providerHostIsBlocked(url.hostname)) throw new ProviderError("BAD_REQUEST", "Provider URL is not allowed"); return url.toString().replace(/\/$/, ""); }
export async function createProvider(principal: CurrentPrincipal, input: Omit<ProviderConfigDto, "id" | "hasApiKey"> & { apiKey?: string }) { requireEncryption(); const record: StoredProvider = { id: randomUUID(), ownerId: principal.id, name: input.name, baseUrl: validateProviderBaseUrl(input.baseUrl), model: input.model, wireApi: input.wireApi, hasApiKey: Boolean(input.apiKey), encryptedApiKey: input.apiKey ? encryptProviderSecret(input.apiKey) : null }; if (inMemoryForTest) { providers.push(record); return dto(record); } const saved = await getPrisma().providerConfig.create({ data: { id: record.id, ownerId: record.ownerId, name: record.name, baseUrl: record.baseUrl, model: record.model, wireApi: record.wireApi, encryptedApiKey: record.encryptedApiKey } }); return dto({ ...saved, wireApi: saved.wireApi as WireApi, hasApiKey: Boolean(saved.encryptedApiKey) }); }
export async function listProviders(principal: CurrentPrincipal) { if (inMemoryForTest) return providers.filter((x) => x.ownerId === principal.id).map(dto); return (await getPrisma().providerConfig.findMany({ where: { ownerId: principal.id } })).map((x) => dto({ ...x, wireApi: x.wireApi as WireApi, hasApiKey: Boolean(x.encryptedApiKey) })); }
export async function getOwnedProvider(principal: CurrentPrincipal, id: string): Promise<StoredProvider> { if (inMemoryForTest) { const found = providers.find((x) => x.id === id && x.ownerId === principal.id); if (!found) throw new ProviderError("NOT_FOUND", "Provider was not found"); return found; } const found = await getPrisma().providerConfig.findFirst({ where: { id, ownerId: principal.id } }); if (!found) throw new ProviderError("NOT_FOUND", "Provider was not found"); return { ...found, wireApi: found.wireApi as WireApi, hasApiKey: Boolean(found.encryptedApiKey) }; }
export async function getOwnedProviderSecret(principal: CurrentPrincipal, id: string) { const provider = await getOwnedProvider(principal, id); if (!provider.encryptedApiKey) throw new ProviderError("BAD_REQUEST", "Provider has no configured API key"); return { provider, apiKey: decryptProviderSecret(provider.encryptedApiKey) }; }
export async function updateProvider(principal: CurrentPrincipal, id: string, input: Partial<Omit<ProviderConfigDto, "id" | "hasApiKey">> & { apiKey?: string }) { requireEncryption(); const old = await getOwnedProvider(principal, id); const next: StoredProvider = { ...old, ...(input.name !== undefined ? { name: input.name } : {}), ...(input.model !== undefined ? { model: input.model } : {}), ...(input.wireApi !== undefined ? { wireApi: input.wireApi } : {}), ...(input.baseUrl !== undefined ? { baseUrl: validateProviderBaseUrl(input.baseUrl) } : {}), ...(input.apiKey !== undefined ? { encryptedApiKey: input.apiKey ? encryptProviderSecret(input.apiKey) : null } : {}) }; if (inMemoryForTest) { providers = providers.map((x) => x.id === id ? next : x); return dto(next); } const saved = await getPrisma().providerConfig.update({ where: { id }, data: { name: next.name, model: next.model, wireApi: next.wireApi, baseUrl: next.baseUrl, encryptedApiKey: next.encryptedApiKey } }); return dto({ ...saved, wireApi: saved.wireApi as WireApi, hasApiKey: Boolean(saved.encryptedApiKey) }); }
export async function deleteProvider(principal: CurrentPrincipal, id: string) { await getOwnedProvider(principal, id); if (inMemoryForTest) { providers = providers.filter((p) => p.id !== id); presets = presets.filter((p) => p.providerId !== id); return; } await getPrisma().providerConfig.delete({ where: { id } }); }
export async function createPreset(principal: CurrentPrincipal, input: Omit<ModelPresetDto, "id">) { await getOwnedProvider(principal, input.providerId); const p: StoredPreset = { ...input, id: randomUUID(), ownerId: principal.id }; if (inMemoryForTest) { presets.push(p); return { ...p, ownerId: undefined } as ModelPresetDto; } const saved = await getPrisma().modelPreset.create({ data: p }); return { id: saved.id, name: saved.name, providerId: saved.providerId, model: saved.model, temperature: saved.temperature, maxTokens: saved.maxTokens }; }
export async function listPresets(principal: CurrentPrincipal) { if (inMemoryForTest) return presets.filter((p) => p.ownerId === principal.id).map(({ ownerId: _, ...p }) => p); return (await getPrisma().modelPreset.findMany({ where: { ownerId: principal.id } })).map(({ id, name, providerId, model, temperature, maxTokens }) => ({ id, name, providerId, model, temperature, maxTokens })); }
export async function resolveModelForWriting(principal: CurrentPrincipal, input: { stepPresetId?: string; workflowPresetId?: string; rolePresetId?: string; userDefaultPresetId?: string }) { const options = await listPresets(principal); for (const id of [input.stepPresetId, input.workflowPresetId, input.rolePresetId, input.userDefaultPresetId]) { const found = id && options.find((p) => p.id === id); if (found) return found; } return null; }
