import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createRequire } from "node:module";
import { mkdir, rm } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";

const require = createRequire(import.meta.url); const { DatabaseSync } = require("node:sqlite") as typeof import("node:sqlite");
const path = resolve(process.cwd(), ".tmp", `writing-prisma-${process.pid}.db`); const url = `file:./../.tmp/${path.split(sep).at(-1)}`;
let repo: typeof import("@/lib/writing/repository");

describe("writing Prisma persistence", () => {
  beforeAll(async () => { await mkdir(dirname(path), { recursive: true }); const db = new DatabaseSync(path); db.exec(`CREATE TABLE User (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME NOT NULL); CREATE TABLE WritingEvidence (id TEXT PRIMARY KEY, ownerId TEXT NOT NULL, sessionId TEXT NOT NULL, title TEXT NOT NULL, excerpt TEXT NOT NULL, provenanceJson TEXT NOT NULL, url TEXT, verificationStatus TEXT NOT NULL, userConfirmedAt DATETIME, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX WritingEvidence_ownerId_sessionId_verificationStatus_idx ON WritingEvidence(ownerId,sessionId,verificationStatus); CREATE TABLE WritingArtifact (id TEXT PRIMARY KEY, ownerId TEXT NOT NULL, sessionId TEXT NOT NULL, stage TEXT NOT NULL, contentHash TEXT NOT NULL, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE WritingCheckpoint (id TEXT PRIMARY KEY, ownerId TEXT NOT NULL, sessionId TEXT NOT NULL, stage TEXT NOT NULL, artifactId TEXT, createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX WritingCheckpoint_ownerId_sessionId_createdAt_idx ON WritingCheckpoint(ownerId,sessionId,createdAt); CREATE TABLE ProviderConnectionRateLimit (ownerId TEXT NOT NULL, providerId TEXT NOT NULL, windowStartedAt DATETIME NOT NULL, attempts INTEGER NOT NULL, PRIMARY KEY(ownerId,providerId));`); db.close(); process.env.DATABASE_URL = url; vi.resetModules(); delete (globalThis as { __prisma?: unknown }).__prisma; repo = await import("@/lib/writing/repository"); });
  afterAll(async () => { const prisma = (globalThis as { __prisma?: { $disconnect(): Promise<void> } }).__prisma; await prisma?.$disconnect(); delete (globalThis as { __prisma?: unknown }).__prisma; delete process.env.DATABASE_URL; await rm(path, { force: true }); });
  it("persists candidate confirmation, immutable checkpoints, owner resume and atomic rate limiting", async () => { const candidate = { id: "e1", title: "Focus paper", excerpt: "One fact. Another fact.", url: "https://example.test/p", authors: ["A"], titleAuthorMatch: "matched" as const, provenance: { sourceKind: "openalex" as const, sourceLabel: "OpenAlex", retrievedAt: "2026-08-24T00:00:00.000Z" }, verificationStatus: "needs_review" as const }; await repo.persistCandidate("owner-a", "s1", candidate); await expect(repo.confirmCandidate("owner-b", "s1", "e1")).resolves.toBeNull(); await expect(repo.confirmCandidate("owner-a", "s1", "e1")).resolves.toMatchObject({ verificationStatus: "verified" }); let previous: import("@/lib/writing/types").WritingStage | null = null; for (const stage of ["evidence", "verified_sources", "outline", "draft", "evidence_link", "human_review", "export"] as const) { const checkpoint = await repo.persistStage("owner-a", "s1", previous, stage, stage); expect(checkpoint.artifactId).toBeTruthy(); previous = stage; } await expect(repo.resumeWriting("owner-a", "s1")).resolves.toMatchObject({ stage: "export" }); await expect(repo.resumeWriting("owner-b", "s1")).resolves.toBeNull(); const allowed = await Promise.all(Array.from({ length: 8 }, () => repo.consumeConnectionTest("owner-a", "p1"))); expect(allowed.filter(Boolean)).toHaveLength(1); });
});
